version: '3'
services:
  postgres:
    container_name: airflowmeta_example
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: airflow123
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5
  airflow:
    build: .
    image: airflow_compose:latest
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 10
    env_file:
      - config/.env.production
    ports:
      - "8080:8080"
      - "5555:5555"
    depends_on:
      - postgres
    links:
      - postgres:postgres
