version: '3'
services:
  postgres:
    container_name: airflowmeta_example
    image: postgres:9.6.3
    environment:
      POSTGRES_PASSWORD: airflow123
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5
  graphite:
    container_name: airflow_graphite_example
    image: hopsoft/graphite-statsd:latest
    ports:
      - "8880:80"
      - "8881:81"
      - "8125:8125"
      - "8126:8126"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5
  airflow:
    build: .
    image: airflow_compose:latest
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 10
    env_file:
      - config/.env.production
    ports:
      - "8080:8080"
      - "5555:5555"
      - "8793:8793"
    depends_on:
      - postgres
      - graphite
    links:
      - postgres:postgres
      - graphite:graphite