name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is now in a stale state, please let us know if you still are facing problems.'
        stale-pr-message: 'This PR is now in a stale state, please consider closing it OR mentioning the codeowners.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
